version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
     - mysqldata:/var/lib/mysql
    ports:
     - "${MYSQL_PORT:-33066}:3306"
    networks:
     - appnet

  db_pma:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
    - db
    ports:
    - 8082:80
    networks:
     - appnet

  www:
    build:
      context: ./docker/php-apache
      args:
        - PHP_VERSION=8.1
    depends_on:
    - db
    environment:
      LANG: en_US.UTF-8
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html/
    networks:
     - appnet

volumes:
  mysqldata:

networks:
  appnet:
    driver: bridge